name: Hello World

on: 
  pull_request:
    branches: [main]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo ${{github.base_ref}}
        echo ${{github.head_ref}}
