name: Hello World

on: 
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge feature -> dev
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${{github.head_ref}}
          target_branch: dev
          github_token: ${{ github.token }}
