name: show_branch_name

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: mdecoleman/pr-branch-name@1.0.0
      id: vars
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo ${{ steps.vars.outputs.branch }}

