name: show_branch_name

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    id: vars
    steps:
      - uses: mdecoleman/pr-branch-name@1.0.0
      - run: echo ${{ steps.vars.outputs.branch }}

