name: show_branch_name

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - name: shoing branch name
        run: echo ${{ github.payload.pull_request.head.ref }}

