name: show_branch_name

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - name: Extract branch name
        uses: mdecoleman/pr-branch-name@1.0.0
        id: extract_branch
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN }}
      - name: shoing branch name
        run: echo ${{ steps.extract_branch.outputs.branch }}

